# ─────────────────────────────────────────────────────────────────────────────
# 1/f^α noise by fractional differencing (Hosking 1981; Kasdin 1995 §VI)
# ─────────────────────────────────────────────────────────────────────────────
#
# Equation numbers refer to N. J. Kasdin, Proc. IEEE 83, 802 (1995).
#
# Model (Eq. 97): pass i.i.d. N(0, Q_d) innovations w_k through
#     H(z) = 1 / (1 − z⁻¹)^(α/2).
# α = 0 is the identity (white noise), α = 2 is Eq. 96 (a running sum, i.e. a
# random walk), and fractional α interpolates between them.
#
# Spectrum. Kasdin's S is TWO-sided (Eq. 98, with z = e^{jωΔt}):
#     S_d(f) = Q_d Δt / (2 sin(πfΔt))^α   ≈   Q_d Δt^(1−α) / (2πf)^α   (Eq. 99)
# and choosing Q_d = Q / Δt^(1−α) (Eq. 100) makes S_d ≈ Q/(2πf)^α independent
# of Δt. Our `Q_psd` IS Kasdin's Q. Everywhere else this package uses ONE-sided
# spectra (Dutta & Horn p. 498; Ruseckas & Kaulakys Eq. 5), which are 2× larger:
#     S_one(f) = 2 Q_d Δt / |2 sin(πfΔt)|^α  ≈  2 Q_psd / (2πf)^α.
#
# Two equivalent filters (both implemented, so the tests can check one against the other):
#   FIR / MA (Eqs. 102–104): x_n = Σ_{k=0}^{n} h_k w_{n−k},
#                            h_0 = 1, h_k = (α/2 + k − 1) h_{k−1} / k
#   AR / IIR (Eqs. 114–116): x_n = −a_1 x_{n−1} − a_2 x_{n−2} − … + w_n,
#                            a_0 = 1, a_k = (k − 1 − α/2) a_{k−1} / k
#
# Both start from rest (x = 0 before t = 0), so Var[x_n] = Q_d Σ_{k≤n} h_k².
# For α < 1 this converges (the process is asymptotically stationary; Kasdin
# footnote 6: the transient decays as 1/t^α) to Eq. 111. For α ≥ 1 it diverges:
# the process is NONSTATIONARY (∝ ln n at α = 1, cf. Eq. 93).

"""
    FractionalNoiseModel(α, Q_psd)

Gaussian 1/f^α noise generated by Kasdin fractional differencing.

- `α ∈ [0, 2]`: spectral exponent. 0 is white, 1 is pink (1/f), and 2 is Brownian.
- `Q_psd > 0`: Kasdin's Q (Eq. 100). Two-sided S(f) ≈ Q_psd/(2πf)^α, one-sided
  (the convention used throughout this package) S(f) ≈ 2 Q_psd/(2πf)^α.

The sampling interval is **not** part of the model. It is supplied to
`generate_ensemble` and to the theory functions (`dt=`), which then use the
driving variance Q_d = Q_psd · dt^(α−1).

    generate_ensemble(model, tspan, dt, n; rng, method=:fir)

`method = :fir` (default) filters in O(N log N) by FFT, and `method = :ar`
runs the O(N²) recursion. Given the same `rng` state, both return the same samples
to rounding error.

# References
- J. R. M. Hosking, Biometrika 68, 165 (1981)
- N. J. Kasdin, Proc. IEEE 83, 802 (1995), §VI-B,C, Eqs. 97–116
"""
struct FractionalNoiseModel <: AbstractNoiseModel
    α::Float64
    Q_psd::Float64

    function FractionalNoiseModel(α::Real, Q_psd::Real)
        0 <= α <= 2 || throw(ArgumentError("α must lie in [0, 2], got $α"))
        Q_psd > 0 || throw(ArgumentError("Q_psd must be > 0, got $Q_psd"))
        return new(Float64(α), Float64(Q_psd))
    end
end

"""
    driving_variance(model::FractionalNoiseModel, dt) -> Q_d

Variance of the i.i.d. innovations: Q_d = Q / Δt^(1−α) (Kasdin Eq. 100).
This makes the low-frequency PSD independent of dt.
"""
function driving_variance(m::FractionalNoiseModel, dt::Real)
    dt > 0 || throw(ArgumentError("dt must be > 0, got $dt"))
    return m.Q_psd * Float64(dt)^(m.α - 1)
end

"""
    pulse_response(α, N) -> Vector{Float64}

First `N` FIR coefficients h_0 … h_{N−1} of (1 − z⁻¹)^(−α/2), by the
recursion of Kasdin Eq. 104. Julia index k+1 holds h_k.
"""
function pulse_response(α::Real, N::Integer)
    N >= 1 || throw(ArgumentError("N must be ≥ 1, got $N"))
    h = Vector{Float64}(undef, N)
    h[1] = 1.0
    for k in 1:N-1
        h[k+1] = h[k] * (α / 2 + k - 1) / k
    end
    return h
end
pulse_response(m::FractionalNoiseModel, N::Integer) = pulse_response(m.α, N)

"""
    ar_coefficients(α, N) -> Vector{Float64}

First `N` AR coefficients a_0 … a_{N−1} of (1 − z⁻¹)^(+α/2), the inverse
filter, by the recursion of Kasdin Eq. 116.
"""
function ar_coefficients(α::Real, N::Integer)
    N >= 1 || throw(ArgumentError("N must be ≥ 1, got $N"))
    a = Vector{Float64}(undef, N)
    a[1] = 1.0
    for k in 1:N-1
        a[k+1] = a[k] * (k - 1 - α / 2) / k
    end
    return a
end
ar_coefficients(m::FractionalNoiseModel, N::Integer) = ar_coefficients(m.α, N)

"""
    fir_filter(h, W) -> X

Causal linear convolution of every column of `W` with `h`:
X[n, j] = Σ_{k=0}^{n−1} h_k W[n−k, j], computed by zero-padded FFT, so it is
linear rather than circular convolution. `W` may be a matrix or a vector.
"""
function fir_filter(h::AbstractVector{<:Real}, W::AbstractMatrix{<:Real})
    n_t, M = size(W)
    length(h) >= n_t || throw(ArgumentError("need ≥ $n_t filter coefficients, got $(length(h))"))
    nfft = nextprod([2, 3, 5], 2n_t - 1)        # ≥ 2n_t−1 ⇒ no wrap-around
    buf = zeros(nfft)
    buf[1:n_t] .= view(h, 1:n_t)
    Pf = plan_rfft(buf)
    Ĥ = Pf * buf
    Pi = plan_irfft(Ĥ, nfft)
    X = Matrix{Float64}(undef, n_t, M)
    for j in 1:M
        fill!(buf, 0.0)
        buf[1:n_t] .= view(W, :, j)
        y = Pi * (Ĥ .* (Pf * buf))
        X[:, j] .= view(y, 1:n_t)
    end
    return X
end
fir_filter(h::AbstractVector{<:Real}, w::AbstractVector{<:Real}) = vec(fir_filter(h, reshape(w, :, 1)))

"""
    ar_filter(a, W) -> X

Autoregressive recursion x_n = w_n − Σ_{k≥1} a_k x_{n−k} applied to every
column of `W`, starting from rest. It costs O(n_t²) per column and is meant for
cross-checking `fir_filter`.
"""
function ar_filter(a::AbstractVector{<:Real}, W::AbstractMatrix{<:Real})
    n_t, M = size(W)
    length(a) >= n_t || throw(ArgumentError("need ≥ $n_t AR coefficients, got $(length(a))"))
    X = Matrix{Float64}(undef, n_t, M)
    @inbounds for j in 1:M, n in 1:n_t
        s = Float64(W[n, j])
        for k in 1:n-1
            s -= a[k+1] * X[n-k, j]
        end
        X[n, j] = s
    end
    return X
end
ar_filter(a::AbstractVector{<:Real}, w::AbstractVector{<:Real}) = vec(ar_filter(a, reshape(w, :, 1)))

const _CHUNK = 256   # trajectories generated per batch (bounds peak memory)

function generate_ensemble(m::FractionalNoiseModel, tspan, dt::Real, n_samples::Integer;
                           rng::AbstractRNG=default_rng(), method::Symbol=:fir)
    t = _time_grid(tspan, dt)
    _check_nsamples(n_samples)
    n_t = length(t)
    if method === :fir
        coeffs, filt = pulse_response(m.α, n_t), fir_filter
    elseif method === :ar
        coeffs, filt = ar_coefficients(m.α, n_t), ar_filter
    else
        throw(ArgumentError("unknown method :$method (use :fir or :ar)"))
    end
    σ_w = sqrt(driving_variance(m, dt))
    X = Matrix{Float64}(undef, n_t, n_samples)
    for cols in Iterators.partition(1:n_samples, _CHUNK)
        W = randn(rng, n_t, length(cols))
        W .*= σ_w
        X[:, cols] .= filt(coeffs, W)
    end
    return NoiseEnsemble(t, X)
end

# ── Closed-form theory ───────────────────────────────────────────────────────
#
# Only the *stationary* (α < 1, infinitely long record) quantities live here.
# For α ≥ 1 no stationary quantity exists, and these functions throw. Exact
# finite-record expectations valid for every α (including α ≥ 1) belong
# to the validation layer (Step 3), because they depend on which estimator is used.

function _require_dt(dt)
    dt === nothing && throw(ArgumentError(
        "FractionalNoiseModel is defined on a grid: pass dt (e.g. dt = 1e-3)"))
    return Float64(dt)
end

function _require_stationary(m::FractionalNoiseModel)
    m.α < 1 || throw(DomainError(m.α,
        "α ≥ 1 is nonstationary: the variance grows with record length, so no " *
        "stationary variance/autocovariance exists. Use the finite-record " *
        "expectations from the validation layer instead."))
    return nothing
end

"""
    stationary_variance(m::FractionalNoiseModel; dt)

R_d(0) = Q_d Γ(1−α) / Γ²(1−α/2) (Kasdin Eq. 111). Valid only for α < 1.
"""
function stationary_variance(m::FractionalNoiseModel; dt=nothing)
    Δt = _require_dt(dt)
    _require_stationary(m)
    return driving_variance(m, Δt) * gamma(1 - m.α) / gamma(1 - m.α / 2)^2
end

"""
    theoretical_autocovariance(m::FractionalNoiseModel, τ; dt)

Stationary autocovariance R_d(k) at lag k = |τ|/dt (α < 1). It is computed as
R_d(k) = R_d(k−1)·(k−1+α/2)/(k−α/2), which is the ratio of consecutive terms
of Kasdin Eq. 109, starting from Eq. 111. The result is identical to Eqs. 109–110,
but evaluating those with raw Γ functions overflows to NaN from k ≈ 172.
"""
function theoretical_autocovariance(m::FractionalNoiseModel, τ::Real; dt=nothing)
    Δt = _require_dt(dt)
    _require_stationary(m)
    kf = abs(τ) / Δt
    k = round(Int, kf)
    isapprox(kf, k; atol=1e-6) || throw(ArgumentError("τ = $τ is not a multiple of dt = $Δt"))
    R = stationary_variance(m; dt=Δt)
    for j in 1:k
        R *= (j - 1 + m.α / 2) / (j - m.α / 2)
    end
    return R
end

"""
    theoretical_psd(m::FractionalNoiseModel, f; dt=nothing)

- `dt` given: exact one-sided PSD of the filter output,
  2 Q_d Δt / |2 sin(πfΔt)|^α (Kasdin Eq. 98, × 2 for one-sided).
- `dt === nothing`: continuous limit 2 Q_psd / (2πf)^α (Eqs. 99–100, × 2).

Both diverge at f = 0 for α > 0. For α ≥ 1 this is the spectrum of the
filter, not the expected periodogram of a finite record started from rest.
Step 3 provides the latter.
"""
function theoretical_psd(m::FractionalNoiseModel, f::Real; dt=nothing)
    if dt === nothing
        return 2 * m.Q_psd / (2π * abs(f))^m.α
    end
    return 2 * driving_variance(m, dt) * dt / abs(2 * sin(π * f * dt))^m.α
end